name: Windows test


on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  msvc:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        compiler: [cl, clang-cl]
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          choco install ninja
          vcpkg install --triplet=x64-windows eigen3

      - name: Configure
        shell: cmd
        run: |
          mkdir build
          mkdir install
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" & cmake -S . -B ./build -G Ninja -DCMAKE_C_COMPILER:FILEPATH=${{matrix.compiler}} -DCMAKE_CXX_COMPILER:FILEPATH=${{matrix.compiler}} -DCMAKE_PREFIX_PATH:PATH=C:/vcpkg/installed/x64-windows -DCMAKE_INSTALL_PREFIX:PATH=install -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"

      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: cyka-dev-build-dir-${{ matrix.build_type }}
          path: build
          if-no-files-found: error

      - name: Build
        shell: cmd
        run: cmake --build ./build --parallel

      - name: Test
        shell: cmd
        run: |
          cd /d ./build
          ctest . --parallel --output-on-failure

      - name: Install
        shell: cmd
        run: |
          cmake --install ./build
